#!/usr/bin/env bash
# configure_site.sh - probe the current host and generate a RELION site_config.md.
#
# This is the portable "configure the environment" step. Run it once on each machine.
# It auto-detects the RELION install, MPI/GPU/Python, interop tools, and scheduler, then
# emits a site_config.md. Curated, judgement-dependent fields (queue script, scratch dir,
# permission tier, validation fixture) are scraped from a project if you pass --project,
# otherwise left as clearly-marked TODO placeholders for you to fill.
#
# Usage:
#   scripts/configure_site.sh                       # print a generated config to stdout
#   scripts/configure_site.sh --project /path/proj  # also scrape queue/scratch from a job.star
#   scripts/configure_site.sh --apply               # write it to <skill>/site_config.md (active)
#   scripts/configure_site.sh --save                # also save a copy to <skill>/configs/<host>.md
#   scripts/configure_site.sh --apply --save --project <RELION_PROJECT_FIXTURE>
#
# Re-running with --apply overwrites site_config.md. Your curated edits live in configs/<host>.md;
# keep them there and re-apply, or hand-edit site_config.md after generating.
set -uo pipefail

SKILL_DIR="$(cd "$(dirname "$0")/.." && pwd)"
APPLY=0; SAVE=0; PROJECT=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --apply) APPLY=1; shift ;;
    --save) SAVE=1; shift ;;
    --project) PROJECT="${2:-}"; shift 2 ;;
    -h|--help) grep '^# ' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

HOST="$(hostname 2>/dev/null || echo unknown)"
OS="$(. /etc/os-release 2>/dev/null && echo "$PRETTY_NAME" || uname -s)"
KERNEL="$(uname -r 2>/dev/null)"
NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# --- RELION binary ---
RR="$(command -v relion_refine 2>/dev/null || true)"
if [ -z "$RR" ]; then
  for c in ${RELION_BIN:-/opt/relion/bin}/relion_refine "$HOME"/relion*/build/bin/relion_refine /usr/local/bin/relion_refine /opt/relion*/bin/relion_refine; do
    [ -x "$c" ] && RR="$c" && break || true
  done
fi
if [ -n "$RR" ]; then
  BINDIR="$(dirname "$RR")"
  RELVER="$("$RR" --version 2>&1 | grep -i 'RELION version' | head -1 | sed 's/^ *//')"
  ONPATH=$(command -v relion_refine >/dev/null 2>&1 && echo "yes (on PATH)" || echo "no (full path: $RR)")
else
  BINDIR="NOT FOUND"; RELVER="NOT FOUND"; ONPATH="no"
fi

prog() { command -v "$1" >/dev/null 2>&1 && echo "yes" || echo "NO"; }

# --- compute ---
MPIRUN="$(command -v mpirun 2>/dev/null || echo 'NOT FOUND')"
MPIVER="$([ "$MPIRUN" != 'NOT FOUND' ] && mpirun --version 2>&1 | head -1 || true)"
if command -v nvidia-smi >/dev/null 2>&1; then
  GPUS="$(nvidia-smi --query-gpu=name,memory.total,driver_version --format=csv,noheader 2>/dev/null | sed 's/^/  - /' )"
  CUDA="$(nvidia-smi 2>/dev/null | grep -oE 'CUDA Version: [0-9.]+' | head -1)"
  [ -z "$GPUS" ] && GPUS="  - (nvidia-smi present but query failed; GPUs may be on worker nodes only)"
else
  GPUS="  - none on this node (CPU-only, or GPUs only on cluster workers)"; CUDA=""
fi
PY="$(command -v python3 2>/dev/null) ($(python3 --version 2>&1))"

# --- interop tools ---
CS2STAR="$(command -v csparc2star.py 2>/dev/null || echo 'NOT FOUND — set path here if you use cryoSPARC interop')"
CRYODRGN="$(command -v cryodrgn 2>/dev/null || echo 'NOT FOUND on PATH — likely in a conda env (conda env list | grep -i cryodrgn)')"

# --- scheduler ---
SCHED="none detected"
for q in sbatch qsub bsub; do command -v "$q" >/dev/null 2>&1 && SCHED="$q ($(command -v "$q"))" && break; done

# --- scrape queue/scratch from a project's job.star files (optional) ---
# Scan ALL job.star (different job types populate different fields), taking the
# first non-empty value of each field. A compute job (Refine3D/Class3D) carries
# scratch_dir/queue; an Import/Select job may not — so don't trust just one file.
QSUB="TODO"; QSCRIPT="TODO"; QNAME="TODO"; SCRATCH="TODO"
if [ -n "$PROJECT" ] && [ -d "$PROJECT" ]; then
  mapfile -t JSLIST < <(find "$PROJECT" -maxdepth 3 -name job.star 2>/dev/null | head -200)
  first_val() {  # $1 = joboption name; echoes first non-empty quoted/bare value across all job.star
    local name="$1" v=""
    for f in "${JSLIST[@]}"; do
      v="$(grep -E "^[[:space:]]*$name[[:space:]]" "$f" 2>/dev/null | head -1 | sed -E "s/^[[:space:]]*$name[[:space:]]+//; s/^\"//; s/\"[[:space:]]*$//; s/[[:space:]]+$//")"
      [ -n "$v" ] && { echo "$v"; return; }
    done
  }
  v="$(first_val qsub)";        [ -n "$v" ] && QSUB="$v"
  v="$(first_val qsubscript)";  [ -n "$v" ] && QSCRIPT="$v"
  v="$(first_val queuename)";   [ -n "$v" ] && QNAME="$v"
  v="$(first_val scratch_dir)"; [ -n "$v" ] && SCRATCH="$v"
fi

read -r -d '' BODY <<EOF
---
name: relion-site-config
description: Site-specific RELION environment for host \`$HOST\`. Auto-generated by scripts/configure_site.sh on $NOW. Load before any environment-dependent action.
---

# Site config — host \`$HOST\`

Auto-generated by \`scripts/configure_site.sh\` on $NOW. Re-run it after a RELION upgrade or when moving machines. **Fields marked TODO are judgement-dependent — fill them in (or re-run with \`--project <a RELION project>\` to scrape queue/scratch from a real job.star).**

## RELION install

| Field | Value |
|---|---|
| Host | \`$HOST\` ($OS, $KERNEL) |
| RELION version | $RELVER |
| Binary dir | \`$BINDIR\` |
| On PATH | $ONPATH |

**Program families present:** refine_mpi=$(prog relion_refine_mpi), preprocess=$(prog relion_preprocess), motioncorr=$(prog relion_run_motioncorr), ctffind=$(prog relion_run_ctffind), ctf_refine=$(prog relion_ctf_refine), motion_refine=$(prog relion_motion_refine), postprocess=$(prog relion_postprocess), mask_create=$(prog relion_mask_create), particle_subtract=$(prog relion_particle_subtract), class_ranker=$(prog relion_class_ranker), star_handler=$(prog relion_star_handler), image_handler=$(prog relion_image_handler), convert_star=$(prog relion_convert_star), helix_toolbox=$(prog relion_helix_toolbox), tomo=$(prog relion_tomo_reconstruct_particle), blush=$(prog relion_python_blush), dynamight=$(prog relion_python_dynamight), modelangelo=$(prog relion_python_modelangelo), topaz=$(prog relion_python_topaz).

## Compute

| Field | Value |
|---|---|
| MPI | $MPIRUN ${MPIVER:+— $MPIVER} |
| CUDA | ${CUDA:-unknown} |
| Python | $PY |

GPUs:
$GPUS

> Watch GPU memory: large boxes / high \`--K\` can OOM. Reduce \`--pool\`, particles/box per GPU, or use \`--free_gpu_memory\`.

## Queue / submission

| Field | Value |
|---|---|
| Scheduler | $SCHED |
| \`qsub\` (submit cmd) | $QSUB |
| \`qsubscript\` (template) | $QSCRIPT |
| \`queuename\` | $QNAME |
| \`scratch_dir\` | $SCRATCH |

> If TODO: read a working \`job.star\` from one of your own RELION jobs and copy its \`qsub\`/\`qsubscript\`/\`queuename\`/\`scratch_dir\` here, or re-run \`configure_site.sh --project <your_project> --apply\`.

## External tools for interop (verify before scripting)

| Tool | Status | Used for |
|---|---|---|
| pyem / \`csparc2star.py\` | $CS2STAR | RELION <-> cryoSPARC (\`16_interop_cryosparc.md\`) |
| cryoDRGN | $CRYODRGN | RELION -> cryoDRGN (\`17_interop_cryodrgn.md\`) |
| ChimeraX / Coot / Phenix | sibling skills \`chimerax\`, \`coot\`, \`phenix\` | map/model handoff (\`18_interop_chimerax_coot_phenix.md\`) |
| Topaz / crYOLO | \`relion_python_topaz\`=$(prog relion_python_topaz); crYOLO via \`cryolo\` skill | picking interop (\`19_interop_coordinates.md\`) |

## Validation / scratch fixture (optional, READ-ONLY)

| Field | Value |
|---|---|
| Path | ${PROJECT:-TODO — a real RELION project you can inspect read-only} |

> Treat any real project as read-only unless you explicitly intend to write into it.

## Permission level on this host

> Default until you say otherwise: **Read-only + Generate (tiers R/G).** To allow command execution / job launch (tier X), state it here and the skill will still ask per-action before the first \`sbatch\` / \`relion_*_mpi\` of a session. Edit this line to record what you have granted.

## What the user still needs to supply (per task)

1. The **project directory** to inspect or run in (never assumed).
2. For a launch: MPI/thread/GPU counts and the queue (the values above are a starting point, not a decision).
3. For interop: the path to \`csparc2star.py\` / the cryoDRGN env if not recorded above.
4. Explicit "yes, run it" before any tier-X action.
EOF

if [ "$SAVE" -eq 1 ]; then
  mkdir -p "$SKILL_DIR/configs"
  printf '%s\n' "$BODY" > "$SKILL_DIR/configs/$HOST.md"
  echo "[OK] saved $SKILL_DIR/configs/$HOST.md" >&2
fi
if [ "$APPLY" -eq 1 ]; then
  printf '%s\n' "$BODY" > "$SKILL_DIR/site_config.md"
  echo "[OK] wrote active config $SKILL_DIR/site_config.md (host $HOST)" >&2
else
  printf '%s\n' "$BODY"
  echo >&2
  echo "[dry-run] printed only. Use --apply to write site_config.md, --save to keep configs/$HOST.md." >&2
fi
