#!/usr/bin/env bash
# Sanitized StructAgent A2A sender template.
# Requires:
#   STRUCTAGENT_A2A_URL   e.g. http://127.0.0.1:18800
#   STRUCTAGENT_A2A_TOKEN generated by your own gateway
# Optional:
#   STRUCTAGENT_A2A_TIMEOUT          request timeout in seconds, default 180
#   STRUCTAGENT_A2A_RETRIES          send retries, default 3
#   STRUCTAGENT_A2A_HEALTH_ATTEMPTS  gateway readiness checks, default 10

set -euo pipefail

A2A_URL="${STRUCTAGENT_A2A_URL:-http://127.0.0.1:18800}"
A2A_TOKEN="${STRUCTAGENT_A2A_TOKEN:?Set STRUCTAGENT_A2A_TOKEN}"
AGENT_ID=""
MESSAGE=""
TIMEOUT="${STRUCTAGENT_A2A_TIMEOUT:-180}"
RETRIES="${STRUCTAGENT_A2A_RETRIES:-3}"
HEALTH_ATTEMPTS="${STRUCTAGENT_A2A_HEALTH_ATTEMPTS:-10}"
BACKOFF_SECONDS="${STRUCTAGENT_A2A_BACKOFF_SECONDS:-5}"

usage() {
  echo "Usage: $0 --to <agent_id> --message <text> [--timeout 180] [--retries 3]" >&2
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --to) AGENT_ID="$2"; shift 2 ;;
    --message) MESSAGE="$2"; shift 2 ;;
    --timeout) TIMEOUT="$2"; shift 2 ;;
    --retries) RETRIES="$2"; shift 2 ;;
    *) usage ;;
  esac
done

[[ -n "$AGENT_ID" && -n "$MESSAGE" ]] || usage

MSG_ID="structagent-$(date +%s)-$$"

check_gateway() {
  local card_url="$A2A_URL/.well-known/agent-card.json"
  local attempt
  for attempt in $(seq 1 "$HEALTH_ATTEMPTS"); do
    if curl -sf --max-time 5 "$card_url" >/dev/null 2>&1; then
      return 0
    fi
    echo "Gateway not ready, waiting... (attempt $attempt/$HEALTH_ATTEMPTS)" >&2
    sleep 2
  done
  echo "ERROR: gateway not reachable at $card_url" >&2
  return 1
}

build_payload() {
  python3 - "$MSG_ID" "$AGENT_ID" "$MESSAGE" <<'PY'
import json, sys
msg_id, agent_id, text = sys.argv[1:4]
print(json.dumps({
  "jsonrpc": "2.0",
  "method": "message/send",
  "id": msg_id,
  "params": {
    "message": {
      "role": "user",
      "messageId": msg_id,
      "agentId": agent_id,
      "parts": [{"type": "text", "text": text}]
    }
  }
}))
PY
}

send_message() {
  local payload response attempt wait_seconds
  payload="$(build_payload)"

  for attempt in $(seq 1 "$RETRIES"); do
    echo "Sending to $AGENT_ID (attempt $attempt/$RETRIES)..." >&2
    if response=$(curl -sf --max-time "$TIMEOUT" \
      -X POST "$A2A_URL/a2a/jsonrpc" \
      -H "Content-Type: application/json" \
      -H "Authorization: Bearer $A2A_TOKEN" \
      -d "$payload" 2>&1); then
      printf '%s\n' "$response"
      return 0
    fi

    if [[ "$attempt" -lt "$RETRIES" ]]; then
      wait_seconds=$((BACKOFF_SECONDS * attempt))
      echo "Send failed; retrying in ${wait_seconds}s" >&2
      sleep "$wait_seconds"
    fi
  done

  echo "ERROR: failed after $RETRIES attempts" >&2
  return 1
}

check_gateway
send_message
